# Generated by Django 4.1.7 on 2023-03-27 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_aids_be_aids_decode_aids_se_aids_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='It_BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='It_BE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='It_Decode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='It_decode/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='It_SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='It_SE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='It_TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='It_TE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
