# Generated by Django 4.1.7 on 2023-03-27 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_it_be_it_decode_it_se_it_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='civil_BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='civil_BE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_Decode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='civil_decode/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='civil_SE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='civil_TE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Etc_BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Etc_BE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Etc_Decode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Etc_decode/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Etc_SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Etc_SE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Etc_TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Etc_TE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Mech_BE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Mech_BE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Mech_Decode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Mech_decode/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Mech_SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Mech_SE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Mech_TE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Mech_TE/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
