# Generated by Django 4.1.7 on 2023-03-27 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_civil_be_civil_decode_civil_se_civil_te_etc_be_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Q_paper/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
