# Generated by Django 4.1.7 on 2023-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_q_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_p',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
